### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by bms63**
Sorry I deleted master and it closed you PR @SHAESEN2.  aplogies

### CODE REVIEW

**Comment by laxamanaj** [comment]
> Sorry I deleted master and it closed you PR @SHAESEN2. aplogies

No worries.  Thanks for updating/renaming `main` branch.  Thanks for re-opening this PR!

**Comment by laxamanaj** [comment]
Re-posting my question : 

Thanks, @SHAESEN2 . For the install steps, I used this code to install the pilot3 package

```
# install Pilot 3 package
remotes::install_github(
repo = "RConsortium/submissions-pilot3-utilities",
host = "http://api.github.com/",
upgrade = "never",
force = TRUE
)

```
Do you know what the difference is between the devtools::install_github() and the one above is?  

Actually, after googling a bit more, this conversation https://github.com/r-lib/usethis/issues/733 and this conversation https://github.com/r-lib/rlang/issues/769 , currently in their corresponding repos have now changed to `pak::pkg_install()` instead, which seems to be the more current approach : https://github.com/r-lib/pak

**Comment by bms63** [comment]
@SHAESEN2  and @laxamanaj I fixed the R CMD checks, but the styler one is falling over.  I think it might be due to an outage on CRAN or RSPM.  Let's keep an eye on that one.

**Comment by robertdevine** [comment]
@laxamanaj, @bms63, @SHAESEN2 - as noted renv::install( ) works fine and does not issue any [warnings](https://github.com/RConsortium/submissions-pilot3-utilities/pull/6#issuecomment-1582850049). thx.

**Pull request merged**
